function data_table= hard_save(data_table,Curve_id,...
    DS_comp, GS_comp, Aperture, Vgs_min, Vgs_max, ...
    vDS, N_points, Dwell_time, Dwell_voltage,N_cycles, Ids, Vds, Vds_expected, Igs, Vgs, Vgs_expected, t)
%hard_save Creates a hard save, a global data table to keep track of every
%not deleted curve.

if ~istable(data_table)
    data_table = table({Curve_id}, DS_comp, GS_comp, Aperture, Vgs_min, Vgs_max,N_cycles, vDS, N_points, Dwell_time, Dwell_voltage, ...
       {Ids}, {Vds}, {Vds_expected},{Igs}, {Vgs}, {Vgs_expected}, {t}, ...
        'VariableNames', {'Curve_id','DS_comp', 'GS_comp','Aperture', 'Vgs_min', 'Vgs_max', 'N_cycles', ...
        'vDS', 'N_points', 'Dwell_time','Dwell_voltage', 'Ids', 'Vds', 'Vds_expected',...
        'Igs', 'Vgs', 'Vgs_expected', 't'});
else
    data_table(end+1,:) = {{Curve_id},DS_comp, GS_comp, Aperture, Vgs_min, Vgs_max,N_cycles, vDS, N_points, Dwell_time, Dwell_voltage, ...
        {Ids}, {Vds}, {Vds_expected},{Igs}, {Vgs}, {Vgs_expected}, {t}};

end